package routes

import (
	"github.com/VieiraGabrielAlexandre/api_comics_and_books/src/controllers"
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
	"log"
	"net/http"
)

func HandleRequests() {
	r := mux.NewRouter().StrictSlash(true)

	r.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8081/swagger/doc.json"), // Replace with your API definition URL
	))

	r.HandleFunc("/comics", controllers.GetAllPaginate).Methods("GET")
	r.HandleFunc("/comics", controllers.Create).Methods("POST")
	r.HandleFunc("/comics/{id}", controllers.GetByID).Methods("GET")
	r.HandleFunc("/comics/{id}", controllers.Update).Methods("PUT")
	r.HandleFunc("/comics/{id}", controllers.Delete).Methods("DELETE")

	http.Handle("/", r)

	println("Running server on port 8081")
	log.Fatalf(http.ListenAndServe(":8081", nil).Error())
}
